version: '3'

services:
  nginx:
    image: redwav/redwav:latest
    container_name: Redwav-Frontend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certs:/etc/ssl/certs/
      - ./ssl/private:/etc/ssl/private/
      - ./dist:/react/build/

