pipeline {
    agent { 
        label 'slave-node' 
    }
    stages {
        stage('Build') {
            steps {
                dir("App") {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
